In [19]:
# Neatness of code:
%load_ext pycodestyle_magic
%pycodestyle_on

The pycodestyle_magic extension is already loaded. To reload it, use:
  %reload_ext pycodestyle_magic

In [20]:
# Load packages:
import sqlite3
import pandas as pd
import numpy as np
pd.set_option('display.max_colwidth', None)
pd.set_option('display.max_rows', 100) 
# First we take a look at the database struture
conn = sqlite3.connect('../db.sqlite3')
pd.read_sql(""" SELECT * FROM sqlite_master;""", conn)

,type,name,tbl_name,rootpage,sql
0,table,Countries,Countries,2,"CREATE TABLE ""Countries"" (\n""CountryCode"" TEXT,\n ""ShortName"" TEXT,\n ""TableName"" TEXT,\n ""LongName"" TEXT,\n ""Alpha2Code"" TEXT,\n ""CurrencyUnit"" TEXT,\n ""SpecialNotes"" TEXT,\n ""Region"" TEXT,\n ""IncomeGroup"" TEXT,\n ""Wb2Code"" TEXT,\n ""NationalAccountsBaseYear"" TEXT,\n ""NationalAccountsReferenceYear"" TEXT,\n ""SnaPriceValuation"" TEXT,\n ""LendingCategory"" TEXT,\n ""OtherGroups"" TEXT,\n ""SystemOfNationalAccounts"" TEXT,\n ""AlternativeConversionFactor"" TEXT,\n ""PppSurveyYear"" TEXT,\n ""BalanceOfPaymentsManualInUse"" TEXT,\n ""ExternalDebtReportingStatus"" TEXT,\n ""SystemOfTrade"" TEXT,\n ""GovernmentAccountingConcept"" TEXT,\n ""ImfDataDisseminationStandard"" TEXT,\n ""LatestPopulationCensus"" TEXT,\n ""LatestHouseholdSurvey"" TEXT,\n ""SourceOfMostRecentIncomeAndExpenditureData"" TEXT,\n ""VitalRegistrationComplete"" TEXT,\n ""LatestAgriculturalCensus"" TEXT,\n ""LatestIndustrialData"" TEXT,\n ""LatestTradeData"" TEXT,\n ""LatestWaterWithdrawalData"" TEXT\n)"
1,table,CountryNotes,CountryNotes,39,"CREATE TABLE ""CountryNotes"" (\n""CountryCode"" TEXT,\n ""IndicatorCode"" TEXT,\n ""Description"" TEXT\n)"
2,table,Footnotes,Footnotes,232,"CREATE TABLE ""Footnotes"" (\n""CountryCode"" TEXT,\n ""IndicatorCode"" TEXT,\n ""Year"" TEXT,\n ""Description"" TEXT\n)"
3,table,CountryIndicators,CountryIndicators,3142,"CREATE TABLE ""CountryIndicators"" (\n""CountryCode"" TEXT,\n ""IndicatorCode"" TEXT,\n ""Year"" INTEGER,\n ""Value"" REAL\n)"
4,table,Indicators,Indicators,4212,"CREATE TABLE ""Indicators"" (\n""IndicatorCode"" TEXT,\n ""Topic"" TEXT,\n ""IndicatorName"" TEXT,\n ""ShortDefinition"" TEXT,\n ""LongDefinition"" TEXT,\n ""UnitOfMeasure"" TEXT,\n ""Periodicity"" TEXT,\n ""BasePeriod"" TEXT,\n ""OtherNotes"" TEXT,\n ""AggregationMethod"" TEXT,\n ""LimitationsAndExceptions"" TEXT,\n ""NotesFromOriginalSource"" TEXT,\n ""GeneralComments"" TEXT,\n ""Source"" TEXT,\n ""StatisticalConceptAndMethodology"" TEXT,\n ""DevelopmentRelevance"" TEXT,\n ""RelatedSourceLinks"" TEXT,\n ""OtherWebLinks"" TEXT,\n ""RelatedIndicators"" TEXT,\n ""LicenseType"" TEXT\n)"
5,table,IndicatorsNotes,IndicatorsNotes,3143,"CREATE TABLE ""IndicatorsNotes"" (\n""IndicatorCode"" TEXT,\n ""Year"" TEXT,\n ""Description"" TEXT\n)"
6,table,EstimatedGPDGrowth,EstimatedGPDGrowth,59596,"CREATE TABLE ""EstimatedGPDGrowth"" (\n\t""CountryCode""\tTEXT NOT NULL,\n\t""Year""\tINTEGER NOT NULL,\n\t""Value""\tREAL\n)"

6:39: W291 trailing whitespace

READ ONLY THE PARAMETERS INCLUDED IN A LIST

In [53]:
#The list has _ becase is required for another function to work
selected_par = [('NE_CON_PETC_KD', 'TX_VAL_MRCH_CD_WT', 'NE_CON_GOVT_CD',
       'NE_GDI_TOTL_KD', 'NE_CON_PETC_CD', 'NY_GDP_FCST_KD',
       'NY_GNP_MKTP_CD', 'NY_GDP_FCST_CD', 'NY_GDY_TOTL_KD',
       'NE_CON_PRVT_PP_CD', 'NV_SRV_TETC_CD', 'NY_GDP_MKTP_KD',
       'BX_GSR_GNFS_CD', 'CM_MKT_TRAD_CD', 'NE_CON_TOTL_KD',
       'NE_CON_TETC_KD', 'NE_DAB_TOTL_CD', 'NY_GNP_MKTP_KD',
       'NY_GDP_MKTP_PP_KD', 'NE_CON_TETC_CD', 'NE_CON_PRVT_KD',
       'NY_GDS_TOTL_CD', 'NY_GNP_MKTP_PP_KD', 'NE_DAB_TOTL_KD',
       'BX_GSR_TOTL_CD', 'NE_EXP_GNFS_KD', 'NY_ADJ_NNTY_KD')]

new_strings = []

for par in selected_par:
    new_string = par.replace("_", ".")
    new_strings.append(new_string)


#selected_par = selected_par.replace("_",".")
#select = pd.DataFrame(selected_par)
#selected = select.columns.str.replace("_",".")
type(selected_par)
type(select.loc[:,1])
select.loc[0,0]
selected_par
new_strings

['NE.CON.PETC.KD',
 'TX.VAL.MRCH.CD.WT',
 'NE.CON.GOVT.CD',
 'NE.GDI.TOTL.KD',
 'NE.CON.PETC.CD',
 'NY.GDP.FCST.KD',
 'NY.GNP.MKTP.CD',
 'NY.GDP.FCST.CD',
 'NY.GDY.TOTL.KD',
 'NE.CON.PRVT.PP.CD',
 'NV.SRV.TETC.CD',
 'NY.GDP.MKTP.KD',
 'BX.GSR.GNFS.CD',
 'CM.MKT.TRAD.CD',
 'NE.CON.TOTL.KD',
 'NE.CON.TETC.KD',
 'NE.DAB.TOTL.CD',
 'NY.GNP.MKTP.KD',
 'NY.GDP.MKTP.PP.KD',
 'NE.CON.TETC.CD',
 'NE.CON.PRVT.KD',
 'NY.GDS.TOTL.CD',
 'NY.GNP.MKTP.PP.KD',
 'NE.DAB.TOTL.KD',
 'BX.GSR.TOTL.CD',
 'NE.EXP.GNFS.KD',
 'NY.ADJ.NNTY.KD']

1:1: E265 block comment should start with '# '
3:8: E128 continuation line under-indented for visual indent
4:8: E128 continuation line under-indented for visual indent
5:8: E128 continuation line under-indented for visual indent
6:8: E128 continuation line under-indented for visual indent
7:8: E128 continuation line under-indented for visual indent
8:8: E128 continuation line under-indented for visual indent
9:8: E128 continuation line under-indented for visual indent
10:8: E128 continuation line under-indented for visual indent
19:1: E265 block comment should start with '# '
20:1: E265 block comment should start with '# '
21:1: E265 block comment should start with '# '
23:18: E231 missing whitespace after ','
24:13: E231 missing whitespace after ','

In [63]:


par = pd.read_sql("""SELECT * FROM CountryIndicators
    WHERE CountryIndicators.IndicatorCode IN (new_strings);""", conn)
#new_strings
#('NY.ADJ.NNTY.KD', 'NY.GDP.MKTP.KD')
#"select * from my_table where row_names in ('a', 'b') order by row_names

DatabaseError: Execution failed on sql 'SELECT * FROM CountryIndicators
    WHERE CountryIndicators.IndicatorCode IN (new_strings);': no such column: new_strings

5:1: E265 block comment should start with '# '
6:1: E265 block comment should start with '# '
7:1: E265 block comment should start with '# '

In [61]:
par

      CountryCode   IndicatorCode  Year         Value
0             EAS  NY.GDP.MKTP.KD  1960  1.023739e+12
1             EAP  NY.GDP.MKTP.KD  1960  1.511493e+11
2             EMU  NY.GDP.MKTP.KD  1960  2.491733e+12
3             ECS  NY.GDP.MKTP.KD  1960  4.370695e+12
4             EUU  NY.GDP.MKTP.KD  1960  3.684449e+12
...           ...             ...   ...           ...
13908         YEM  NY.GDP.MKTP.KD  2010  1.998908e+10
13909         ZMB  NY.ADJ.NNTY.KD  2010  9.154224e+09
13910         ZMB  NY.GDP.MKTP.KD  2010  1.264744e+10
13911         ZWE  NY.ADJ.NNTY.KD  2010  5.053561e+09
13912         ZWE  NY.GDP.MKTP.KD  2010  5.202304e+09

[13913 rows x 4 columns]

In [41]:
leyend = pd.read_sql("""SELECT IndicatorName, IndicatorCode FROM Indicators;""", conn)
leyend['IndicatorCode'].isin()

SyntaxError: invalid syntax (<ipython-input-41-18d64df2c3d5>, line 2)

1:80: E501 line too long (86 > 79 characters)
2:23: E225 missing whitespace around operator
3:1: W391 blank line at end of file

Tables we are interested in are Countries, Indicators and CountryIndicators. Actually, we only require CountryIndicators, since there is no point in loading indicators that do not have values for certain countries. CountryIndicators contains only those Indicators for which there are at least some values available.

In [4]:
# Then we load the required data
long = pd.read_sql("""SELECT * FROM CountryIndicators;""", conn)
long

        CountryCode      IndicatorCode  Year         Value
0               ARB        SP.ADO.TFRT  1960  1.335609e+02
1               ARB        SP.POP.DPND  1960  8.779760e+01
2               ARB     SP.POP.DPND.OL  1960  6.634579e+00
3               ARB     SP.POP.DPND.YG  1960  8.102333e+01
4               ARB     MS.MIL.XPRT.KD  1960  3.000000e+06
...             ...                ...   ...           ...
5026216         ZWE  SP.URB.TOTL.IN.ZS  2010  3.319600e+01
5026217         ZWE        SP.URB.GROW  2010  1.279630e+00
5026218         ZWE     DT.DOD.DIMF.CD  2010  5.287290e+08
5026219         ZWE     SN.ITK.VITA.ZS  2010  4.930002e+01
5026220         ZWE  SH.DYN.AIDS.FE.ZS  2010  5.898546e+01

[5026221 rows x 4 columns]

The dataframe is not very useful in this shape, so we need to transform it. Is more interesting to have the Indicators as columns, and the values ordered chronologically (Year) and Alphabetically (CountryCode). This can be achieved using Pandas Multiindexing, where rows are accesed via the Year and the CountryCode. The dataframe can be easily transformed using Pandas.pivot_table()

In [35]:
some_values = ['SP.ADO.TFRT', 'SP.POP.DPND.OL']
long.loc[long['IndicatorCode'].isin(some_values)]

        CountryCode   IndicatorCode  Year       Value
0               ARB     SP.ADO.TFRT  1960  133.560907
2               ARB  SP.POP.DPND.OL  1960    6.634579
80              CSS     SP.ADO.TFRT  1960  162.871212
82              CSS  SP.POP.DPND.OL  1960    7.874999
157             CEB     SP.ADO.TFRT  1960   46.716752
...             ...             ...   ...         ...
5023662         YEM  SP.POP.DPND.OL  2010    4.586596
5024526         ZMB     SP.ADO.TFRT  2010  110.804400
5024528         ZMB  SP.POP.DPND.OL  2010    5.772203
5025487         ZWE     SP.ADO.TFRT  2010  115.000600
5025489         ZWE  SP.POP.DPND.OL  2010    5.813059

[23092 rows x 4 columns]

In [14]:
table = pd.pivot_table(long, values=['Value'],
                       index=['CountryCode','Year'],
                       columns=['IndicatorCode'],
                       aggfunc=np.sum)
table = table.dropna(axis=0, how="any", thresh=50, subset=None, inplace=False)
# table.drop(('Value', 1960), axis = 1, inplace=True)

table

                          Value                                   \
IndicatorCode    AG.AGR.TRAC.NO AG.CON.FERT.PT.ZS AG.CON.FERT.ZS
CountryCode Year
ABW         1985            NaN               NaN            NaN
            1986            NaN               NaN            NaN
            1987            NaN               NaN            NaN
            1988            NaN               NaN            NaN
            1989            NaN               NaN            NaN
...                         ...               ...            ...
ZWE         2006            NaN        210.442742      32.356341
            2007            NaN        171.109177      27.035250
            2008            NaN        147.903481      21.994118
            2009            NaN        186.693038      28.778049
            2010            NaN        215.715190      34.083000

                                                               \
IndicatorCode    AG.LND.AGRI.K2 AG.LND.AGRI.ZS AG.LND.ARBL.HA
CountryCode Year
ABW         1985           20.0      11.111111         2000.0
            1986           20.0      11.111111         2000.0
            1987           20.0      11.111111         2000.0
            1988           20.0      11.111111         2000.0
            1989           20.0      11.111111         2000.0
...                         ...            ...            ...
ZWE         2006       163000.0      42.135195      4100000.0
            2007       162000.0      41.876696      4000000.0
            2008       164500.0      42.522942      4250000.0
            2009       163000.0      42.135195      4100000.0
            2010       162000.0      41.876696      4000000.0

                                                                  \
IndicatorCode    AG.LND.ARBL.HA.PC AG.LND.ARBL.ZS AG.LND.CREL.HA
CountryCode Year
ABW         1985          0.031732      11.111111            NaN
            1986          0.031926      11.111111            NaN
            1987          0.032344      11.111111            NaN
            1988          0.032746      11.111111            NaN
            1989          0.032770      11.111111            NaN
...                            ...            ...            ...
ZWE         2006          0.312311      10.598423      2289312.0
            2007          0.300802      10.339925      1949453.0
            2008          0.314921      10.986170      2235440.0
            2009          0.298812      10.598423      2080405.0
            2010          0.286248      10.339925      1891766.0

                                 ...                        \
IndicatorCode    AG.LND.CROP.ZS  ... per_allsp.cov_pop_tot
CountryCode Year                 ...
ABW         1985            NaN  ...                   NaN
            1986            NaN  ...                   NaN
            1987            NaN  ...                   NaN
            1988            NaN  ...                   NaN
            1989            NaN  ...                   NaN
...                         ...  ...                   ...
ZWE         2006       0.258498  ...                   NaN
            2007       0.258498  ...                   NaN
            2008       0.258498  ...                   NaN
            2009       0.258498  ...                   NaN
            2010       0.258498  ...                   NaN

                                                                   \
IndicatorCode    per_lm_alllm.adq_pop_tot per_lm_alllm.ben_q1_tot
CountryCode Year
ABW         1985                      NaN                     NaN
            1986                      NaN                     NaN
            1987                      NaN                     NaN
            1988                      NaN                     NaN
            1989                      NaN                     NaN
...                                   ...                     ...
ZWE         2006                      NaN                     NaN
            2007                      NaN                     NaN
            2008                      NaN                     NaN
            2009                      NaN                     NaN
            2010                      NaN                     NaN

                                                                    \
IndicatorCode    per_lm_alllm.cov_pop_tot per_sa_allsa.adq_pop_tot
CountryCode Year
ABW         1985                      NaN                      NaN
            1986                      NaN                      NaN
            1987                      NaN                      NaN
            1988                      NaN                      NaN
            1989                      NaN                      NaN
...                                   ...                      ...
ZWE         2006                      NaN                      NaN
            2007                      NaN                      NaN
            2008                      NaN                      NaN
            2009                      NaN                      NaN
            2010                      NaN                      NaN

                                                                   \
IndicatorCode    per_sa_allsa.ben_q1_tot per_sa_allsa.cov_pop_tot
CountryCode Year
ABW         1985                     NaN                      NaN
            1986                     NaN                      NaN
            1987                     NaN                      NaN
            1988                     NaN                      NaN
            1989                     NaN                      NaN
...                                  ...                      ...
ZWE         2006                     NaN                      NaN
            2007                     NaN                      NaN
            2008                     NaN                      NaN
            2009                     NaN                      NaN
            2010                     NaN                      NaN

                                                                   \
IndicatorCode    per_si_allsi.adq_pop_tot per_si_allsi.ben_q1_tot
CountryCode Year
ABW         1985                      NaN                     NaN
            1986                      NaN                     NaN
            1987                      NaN                     NaN
            1988                      NaN                     NaN
            1989                      NaN                     NaN
...                                   ...                     ...
ZWE         2006                      NaN                     NaN
            2007                      NaN                     NaN
            2008                      NaN                     NaN
            2009                      NaN                     NaN
            2010                      NaN                     NaN


IndicatorCode    per_si_allsi.cov_pop_tot
CountryCode Year
ABW         1985                      NaN
            1986                      NaN
            1987                      NaN
            1988                      NaN
            1989                      NaN
...                                   ...
ZWE         2006                      NaN
            2007                      NaN
            2008                      NaN
            2009                      NaN
            2010                      NaN

[11501 rows x 1328 columns]

2:44: E231 missing whitespace after ','

In [33]:
nan = (table.loc[:,('Value','NY.GDP.MKTP.KD.ZG')].isnull().sum().sum())
total = table.shape[0]
percentage = nan / total
percentage
table = table.dropna(axis=1, how="any", thresh=7000, subset=None, inplace=False)

1:19: E231 missing whitespace after ','
1:28: E231 missing whitespace after ','
5:80: E501 line too long (80 > 79 characters)

In [153]:
#table.drop(columns=('Value', '1960'))
table.loc[('ABW', 'AG.LND.AGRI.K2'), ('Value', 1961)]
# table.iloc[0, 0] #With iloc we lost the multiindex capabilities
# table.columns.values
table.loc[:, ('Value', 1960)]

CountryCode  IndicatorCode
ABW          AG.LND.AGRI.K2                NaN
             AG.LND.AGRI.ZS                NaN
             AG.LND.ARBL.HA                NaN
             AG.LND.ARBL.HA.PC             NaN
             AG.LND.ARBL.ZS                NaN
                                      ...
ZWE          SP.URB.TOTL          4.731010e+05
             SP.URB.TOTL.IN.ZS    1.260800e+01
             TG.VAL.TOTL.GD.ZS    4.036124e+01
             TM.VAL.MRCH.CD.WT    2.520000e+08
             TX.VAL.MRCH.CD.WT    1.730000e+08
Name: (Value, 1960), Length: 24513, dtype: float64

1:1: E265 block comment should start with '# '

In [88]:
table['per_allsp_adq_pop_tot']

      per_allsp_adq_pop_tot  per_allsp_adq_pop_tot
Year
1960                    NaN                    NaN
1961                    NaN                    NaN
1962                    NaN                    NaN
1963                    NaN                    NaN
1964                    NaN                    NaN
...                     ...                    ...
2006                    NaN                    NaN
2007                    NaN                    NaN
2008                    NaN                    NaN
2009                    NaN                    NaN
2010                    NaN                    NaN

[25245 rows x 2 columns]

The resulting table has more elements than the original dataframe. This is because the Pandas.pivot_table() generates a table with the maximum number of columns available. For some reason, it creates some columns that do not exist in the original Dataframe. We couldnt explain this, so we had to find another way to obtain a similar result. For this we use a for loop to append consecutively all countries and their Indicator values. This is several times slower than pivot_table, but at least it produces the desired output.

In [162]:
# The table is created with a for loop, indexing all countries
for n in long.CountryCode.unique():
    country2 = long[long['CountryCode'].str.contains(n)][["IndicatorCode", "Year", "Value"]]
    df2 = country2.pivot(index='Year', columns='IndicatorCode', values='Value')
    df2 = df2.fillna(method='ffill')
    df2['Country'] = n
    df = df.append(df2)
# Replace . by _ for easy read of IndicatorCodes
df.columns = df.columns.str.replace(".", "_")
# Show the result
df

ValueError: Plan shapes are not aligned

3:80: E501 line too long (92 > 79 characters)

In [97]:
# Number of Countries
print(len(table["Country"].unique()))
df = table

247

LINEAR MIXED MODEL

In [98]:
import statsmodels.api as sm
import statsmodels.formula.api as smf
import statsmodels.stats.api as sms
from statsmodels.compat import lzip


# Creation of Yt-1 and demonstration Yt-2 is not significative.
df['lag1']=df['NY_GDP_MKTP_KD_ZG'].shift(1)
#df['lag2']=df['NY_GDP_MKTP_KD_ZG'].shift(2)
#df = df[df['NY_GDP_MKTP_KD_ZG'].notna()]
df['Time'] = df.index

df = df.dropna(subset=["NY_GDP_MKTP_KD_ZG","lag1"])

# Countries strings to numeric values:
groups = df[["Country"]].replace(np.unique(df[["Country"]]), list(range(0,len(np.unique(df[["Country"]])))))
groups = pd.to_numeric(groups.Country)

# subset of variables
df_sub = df[["NY_GDP_MKTP_KD_ZG","Country","lag1","Time"]]

# mixed linear model: group + year.
md = smf.mixedlm("NY_GDP_MKTP_KD_ZG ~ lag1", df_sub, groups=groups)#, re_formula="~Time" #df["Country"].to_numpy()
mod = md.fit()
print(mod.summary())
test = sms.jarque_bera(mod.resid)
lzip(name, test)
# extraction of residuals
df['residuals'] = mod.resid
df['Country'] = groups

ModuleNotFoundError: No module named 'statsmodels'

8:11: E225 missing whitespace around operator
9:1: E265 block comment should start with '# '
10:1: E265 block comment should start with '# '
13:43: E231 missing whitespace after ','
16:74: E231 missing whitespace after ','
16:80: E501 line too long (108 > 79 characters)
20:33: E231 missing whitespace after ','
20:43: E231 missing whitespace after ','
20:50: E231 missing whitespace after ','
23:68: E261 at least two spaces before inline comment
23:68: E262 inline comment should start with '# '
23:80: E501 line too long (114 > 79 characters)

REMOVE NA

In [398]:
aa =range(1,len(df))
df.shape # 1018
# Require that many non-NA values.
df.dropna(thresh=np.quantile(aa, 0.8), axis=1).shape # 238
df = df.fillna(method='bfill')
df

,AG_AGR_TRAC_NO,AG_CON_FERT_PT_ZS,AG_CON_FERT_ZS,AG_LND_AGRI_K2,AG_LND_AGRI_ZS,AG_LND_ARBL_HA_PC,AG_LND_ARBL_ZS,AG_LND_CREL_HA,AG_LND_CROP_ZS,AG_LND_EL5M_ZS,...,TM_TAX_TCOM_SM_FN_ZS,TM_TAX_TCOM_SR_ZS,TM_TAX_TCOM_WM_AR_ZS,TM_TAX_TCOM_WM_FN_ZS,PA_NUS_FCRF,SP_DYN_WFRT,SN_ITK_VITA_ZS,lag1,Time,residuals
Year,,,,,,,,,,,,,,,,,,,,,
1978,207256.0,31.460708,62.501114,4305790.0,31.604469,0.322672,3.659207,23263857.00,0.321063,0.966807,...,16.24,2.631466,16.48,16.48,0.938627,1.772463,79.142053,8.298998,1978,-3.912287
1979,224684.0,31.460708,62.501114,4307280.0,31.615406,0.311510,3.651059,22086289.00,0.321579,0.966807,...,16.24,2.631466,16.48,16.48,0.938627,1.772463,79.142053,1.674562,1979,7.412543
1980,236194.0,31.460708,62.501114,4318030.0,31.694310,0.301061,3.644307,22988703.00,0.320548,0.966807,...,16.24,2.631466,16.48,16.48,0.938627,1.772463,79.142053,10.283988,1980,3.185555
1981,255349.0,31.460708,62.501114,4276396.0,31.388717,0.293647,3.668352,23489576.00,0.328646,0.966807,...,16.24,2.631466,16.48,16.48,0.938627,1.772463,79.142053,9.586066,1981,-1.913911
1982,271006.0,31.460708,62.501114,4279693.4,31.412920,0.286004,3.684464,22694791.00,0.340867,0.966807,...,16.24,2.631466,16.48,16.48,0.938627,1.772463,79.142053,4.200517,1982,-7.547549
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2006,246232.0,105.839648,147.059860,5167757.8,35.879107,0.231842,6.111021,45177195.00,0.763536,0.668752,...,4.87,27.984810,0.54,1.39,0.755045,1.772463,83.511128,6.151900,2006,0.350733
2007,246232.0,113.840650,147.059860,5184536.2,35.968260,0.227779,6.174093,44991751.00,0.792123,0.668752,...,4.87,27.984810,0.54,1.39,0.755045,1.772463,81.609172,5.595667,2007,0.267929
2008,246232.0,113.840650,147.059860,5179387.3,35.960223,0.222175,6.145962,43431438.00,0.807465,0.668752,...,4.87,27.984810,0.54,1.39,0.755045,1.772463,77.284119,5.284859,2008,-0.039309
2009,246232.0,100.928484,147.059860,5181688.0,35.983842,0.217309,6.156735,44657086.00,0.813800,0.668752,...,4.87,27.984810,0.54,1.39,0.755045,1.772463,87.802609,4.850218,2009,-1.135412
2010,246232.0,98.720213,147.059860,5190035.8,36.041938,0.214147,6.210370,44594593.87,0.820521,0.668752,...,4.87,27.984810,0.54,1.39,0.755045,1.772463,80.899367,3.575953,2010,0.923909

LASSO
With Lasso, the higher the alpha parameter, the fewer features selected.
The features with the highest absolute coef_ value are considered the most important

In [423]:
from sklearn.feature_selection import SelectFromModel
from sklearn.linear_model import LassoCV

# input
covs = df.copy().drop(["NY_GDP_MKTP_KD_ZG"], 1)
Y = df[['NY_GDP_MKTP_KD_ZG']]

# model
clf = LassoCV(tol=0.1,max_iter=1500).fit(covs, np.ravel(Y))
importance = np.abs(clf.coef_)

# important features 
feature_names = covs.columns
idx_features = (-importance).argsort()[:sum(abs(importance)>0)]
name_features = np.array(feature_names)[idx_features]
print('Selected features: {}'.format(name_features))

Selected features: ['NE_CON_PETC_KD' 'TX_VAL_MRCH_CD_WT' 'NE_CON_GOVT_CD' 'NE_GDI_TOTL_KD'
 'NE_CON_PETC_CD' 'NY_GDP_FCST_KD' 'NY_GNP_MKTP_CD' 'NY_GDP_FCST_CD'
 'NY_GDY_TOTL_KD' 'NE_CON_PRVT_PP_CD' 'NV_SRV_TETC_CD' 'NY_GDP_MKTP_KD'
 'BX_GSR_GNFS_CD' 'CM_MKT_TRAD_CD' 'NE_CON_TOTL_KD' 'NE_CON_TETC_KD'
 'NE_DAB_TOTL_CD' 'NY_GNP_MKTP_KD' 'NY_GDP_MKTP_PP_KD' 'NE_CON_TETC_CD'
 'NE_CON_PRVT_KD' 'NY_GDS_TOTL_CD' 'NY_GNP_MKTP_PP_KD' 'NE_DAB_TOTL_KD'
 'BX_GSR_TOTL_CD' 'NE_EXP_GNFS_KD' 'NY_ADJ_NNTY_KD']

CORRELATIONS

In [428]:
#df[[name_features]]
name_features

array(['NE_CON_PETC_KD', 'TX_VAL_MRCH_CD_WT', 'NE_CON_GOVT_CD',
       'NE_GDI_TOTL_KD', 'NE_CON_PETC_CD', 'NY_GDP_FCST_KD',
       'NY_GNP_MKTP_CD', 'NY_GDP_FCST_CD', 'NY_GDY_TOTL_KD',
       'NE_CON_PRVT_PP_CD', 'NV_SRV_TETC_CD', 'NY_GDP_MKTP_KD',
       'BX_GSR_GNFS_CD', 'CM_MKT_TRAD_CD', 'NE_CON_TOTL_KD',
       'NE_CON_TETC_KD', 'NE_DAB_TOTL_CD', 'NY_GNP_MKTP_KD',
       'NY_GDP_MKTP_PP_KD', 'NE_CON_TETC_CD', 'NE_CON_PRVT_KD',
       'NY_GDS_TOTL_CD', 'NY_GNP_MKTP_PP_KD', 'NE_DAB_TOTL_KD',
       'BX_GSR_TOTL_CD', 'NE_EXP_GNFS_KD', 'NY_ADJ_NNTY_KD'], dtype=object)

In [6]:
#### 1) We find Y: EstimatedGDPGrowth for the next year:
#summ_vars2 = summ_vars[summ_vars['IndicatorName'].str.contains("GDP")]
#summ_vars2[~summ_vars2.IndicatorName.str.contains("% of GDP")]
    # Response variable: GDP growth (annual %): NY.GDP.MKTP.KD.ZG
    # GPD covariate: GDP (constant 2005 US$), NY.GDP.MKTP.KD [look description of response if any doubt].
#long.CountryCode.unique()[1:10]

ERROR! Session/line number was not unique in database. History logging moved to new session 41
7.18.1

1:1: E266 too many leading '#' for block comment
2:1: E265 block comment should start with '# '
3:1: E265 block comment should start with '# '
4:5: E116 unexpected indentation (comment)
5:5: E116 unexpected indentation (comment)
5:80: E501 line too long (105 > 79 characters)
6:1: E265 block comment should start with '# '
7:11: E225 missing whitespace around operator

In [20]:
#### 3) NA & corr analysis: df: 629 rows x 51 columns.
ncol = len(df.columns)
complete = df.apply(lambda x: x.count(), axis=1) #complete cases per row.
    # complete.quantile(np.arange(0.0, 1.1, 0.1))
# We keep 80% complete cases: 51*0.8 =40 
df2 = df[complete>40] # 184 rows x 51 columns
    # CAREFUL: For some countries de response has a lot of NA, we should check this.
mat_corr =df2.T.corr() # transpose matrix, then correlation.
corrY_sort= mat_corr['NY.GDP.MKTP.KD.ZG'].iloc[np.flip(mat_corr['NY.GDP.MKTP.KD.ZG'].abs().argsort())]
    # length of corrY_sort: 241
high_corr=corrY_sort[abs(corrY_sort) > 0.7] # abreviation & correlation.
translation_high_corr = summ_vars[summ_vars['IndicatorCode'].str.contains('|'.join(high_corr.index.tolist()))]
translation_high_corr

,IndicatorCode,Topic,IndicatorName,ShortDefinition,LongDefinition,UnitOfMeasure,Periodicity,BasePeriod,OtherNotes,AggregationMethod,LimitationsAndExceptions,NotesFromOriginalSource,GeneralComments,Source,StatisticalConceptAndMethodology,DevelopmentRelevance,RelatedSourceLinks,OtherWebLinks,RelatedIndicators,LicenseType
292,NE.EXP.GNFS.KD.ZG,Economic Policy & Debt: National accounts: Growth rates,Exports of goods and services (annual % growth),,"Annual growth rate of exports of goods and services based on constant local currency. Aggregates are based on constant 2005 U.S. dollars. Exports of goods and services represent the value of all goods and other market services provided to the rest of the world. They include the value of merchandise, freight, insurance, transport, travel, royalties, license fees, and other services, such as communication, construction, financial, information, business, personal, and government services. They exclude compensation of employees and investment income (formerly called factor services) and transfer payments.",,Annual,,,Weighted average,,,,"World Bank national accounts data, and OECD National Accounts data files.",,,,,,Open
294,NY.GDP.MKTP.KD.ZG,Economic Policy & Debt: National accounts: Growth rates,GDP growth (annual %),,Annual percentage growth rate of GDP at market prices based on constant local currency. Aggregates are based on constant 2005 U.S. dollars. GDP is the sum of gross value added by all resident producers in the economy plus any product taxes and minus any subsidies not included in the value of the products. It is calculated without making deductions for depreciation of fabricated assets or for depletion and degradation of natural resources.,,Annual,,,Weighted average,"Each industry's contribution to growth in the economy's output is measured by growth in the industry's value added. In principle, value added in constant prices can be estimated by measuring the quantity of goods and services produced in a period, valuing them at an agreed set of base year prices, and subtracting the cost of intermediate inputs, also in constant prices. This double-deflation method requires detailed information on the structure of prices of inputs and outputs.\n\nIn many industries, however, value added is extrapolated from the base year using single volume indexes of outputs or, less commonly, inputs. Particularly in the services industries, including most of government, value added in constant prices is often imputed from labor inputs, such as real wages or number of employees. In the absence of well defined measures of output, measuring the growth of services remains difficult.\n\nMoreover, technical progress can lead to improvements in production processes and in the quality of goods and services that, if not properly accounted for, can distort measures of value added and thus of growth. When inputs are used to estimate output, as for nonmarket services, unmeasured technical progress leads to underestimates of the volume of output. Similarly, unmeasured improvements in quality lead to underestimates of the value of output and value added. The result can be underestimates of growth and productivity improvement and overestimates of inflation.\n\nInformal economic activities pose a particular measurement problem, especially in developing countries, where much economic activity is unrecorded. A complete picture of the economy requires estimating household outputs produced for home use, sales in informal markets, barter exchanges, and illicit or deliberately unreported activities. The consistency and completeness of such estimates depend on the skill and methods of the compiling statisticians.\n\nRebasing of national accounts can alter the measured growth rate of an economy and lead to breaks in series that affect the consistency of data over time. When countries rebase their national accounts, they update the weights assigned to various components to better reflect current patterns of production or uses of output. The new base year should represent normal operation of the economy - it should be a year without major shocks or distortions. Some developing countries have not rebased their national accounts for many years. Using an old base year can be misleading because implicit price and volume weights become progressively less relevant and useful.\n\nTo obtain comparable series of constant price data for computing aggregates, the World Bank rescales GDP and value added by industrial origin to a common reference year. Because rescaling changes the implicit weights used in forming regional and income group aggregates, aggregate growth rates are not comparable with those from earlier editions with different base years. Rescaling may result in a discrepancy between the rescaled GDP and the sum of the rescaled components. To avoid distortions in the growth rates, the discrepancy is left unallocated. As a result, the weighted average of the growth rates of the components generally does not equal the GDP growth rate.",,,"World Bank national accounts data, and OECD National Accounts data files.","Gross domestic product (GDP) represents the sum of value added by all its producers. Value added is the value of the gross output of producers less the value of intermediate goods and services consumed in production, before accounting for consumption of fixed capital in production. The United Nations System of National Accounts calls for value added to be valued at either basic prices (excluding net taxes on products) or producer prices (including net taxes on products paid by producers but excluding sales or value added taxes). Both valuations exclude transport charges that are invoiced separately by producers. Total GDP is measured at purchaser prices. Value added by industry is normally measured at basic prices. When value added is measured at producer prices.\n\nGrowth rates of GDP and its components are calculated using the least squares method and constant price data in the local currency. Constant price U.S. dollar series are used to calculate regional and income group growth rates. Local currency series are converted to constant U.S. dollars using an exchange rate in the common reference year.","An economy's growth is measured by the change in the volume of its output or in the real incomes of its residents. The 2008 United Nations System of National Accounts (2008 SNA) offers three plausible indicators for calculating growth: the volume of gross domestic product (GDP), real gross domestic income, and real gross national income. The volume of GDP is the sum of value added, measured at constant prices, by households, government, and industries operating in the economy. GDP accounts for all domestic production, regardless of whether the income accrues to domestic or foreign institutions.",,,,Open
295,NY.GDP.PCAP.KD.ZG,Economic Policy & Debt: National accounts: Growth rates,GDP per capita growth (annual %),,Annual percentage growth rate of GDP per capita based on constant local currency. Aggregates are based on constant 2005 U.S. dollars. GDP per capita is gross domestic product divided by midyear population. GDP at purchaser's prices is the sum of gross value added by all resident producers in the economy plus any product taxes and minus any subsidies not included in the value of the products. It is calculated without making deductions for depreciation of fabricated assets or for depletion and degradation of natural resources.,,Annual,,,Weighted average,,,,"World Bank national accounts data, and OECD National Accounts data files.","For more information, see the metadata for constant U.S. dollar GDP (NY.GDP.MKTP.KD) and total population (SP.POP.TOTL).",,,,,Open
302,NE.IMP.GNFS.KD.ZG,Economic Policy & Debt: National accounts: Growth rates,Imports of goods and services (annual % growth),,"Annual growth rate of imports of goods and services based on constant local currency. Aggregates are based on constant 2005 U.S. dollars. Imports of goods and services represent the value of all goods and other market services received from the rest of the world. They include the value of merchandise, freight, insurance, transport, travel, royalties, license fees, and other services, such as communication, construction, financial, information, business, personal, and government services. They exclude compensation of employees and investment income (formerly called factor services) and transfer payments.",,Annual,,,Weighted average,,,,"World Bank national accounts data, and OECD National Accounts data files.",,,,,,Open
370,NE.CON.GOVT.ZS,Economic Policy & Debt: National accounts: Shares of GDP & other,General government final consumption expenditure (% of GDP),,"General government final consumption expenditure (formerly general government consumption) includes all government current expenditures for purchases of goods and services (including compensation of employees). It also includes most expenditures on national defense and security, but excludes government military expenditures that are part of government capital formation.",,Annual,,,Weighted average,"Because policymakers have tended to focus on fostering the growth of output, and because data on production are easier to collect than data on spending, many countries generate their primary estimate of GDP using the production approach. Moreover, many countries do not estimate all the components of national expenditures but instead derive some of the main aggregates indirectly using GDP (based on the production approach) as the control total.",,,"World Bank national accounts data, and OECD National Accounts data files.","Gross domestic product (GDP) from the expenditure side is made up of household final consumption expenditure, general government final consumption expenditure, gross capital formation (private and public investment in fixed assets, changes in inventories, and net acquisitions of valuables), and net exports (exports minus imports) of goods and services. Such expenditures are recorded in purchaser prices and include net taxes on products.",,,,,Open

in many real applications variables are structured into groups, and group sparsity rather than individual sparsity is desired. 
group LASSO: solutions that are both between and within group sparse.
This way, you obtain solutions that are sparse, meaning that many of the β coefficients will be sent to 0 and your model will make predictions based on the few coefficients that are not 0.

The major advantage of these methods compared to OLS is that they can handle multicollinearity, i.e. a predictor matrix with rank less than the number of its columns.

Another thing to remember is that neither Ridge nor Lasso actually respond well to outlying observations.

LASSO is not a type of model. It is a method for selecting variables and shrinking coefficients to adjust for complexity.

The assumptions are those of the type of model it is applied to, which could be ordinary least squares regression, logistic regression

In [ ]:
#### Helpful comments:
# I want to predict year 2010 bc is what we have.
# we must include in the model Y_{t-1}.
# First we should do feature selection (lasso), then NA imputation, then prediction (quantile regression or gradient boosting.
num_models, k_folds = error.shape
# error is a matrix of shape (number_of_models, k_folds)
print(f'We are considering a grid of {num_models} models, optimized based on {k_folds}-folds cross validation')

# Obtain the mean error across different folds
error = np.mean(error, axis=1)


# Select the minimum error
minimum_error_idx = np.argmin(error)

# Select the parameters associated to mininum error values
optimal_parameters = cv_class.retrieve_parameters_value(minimum_error_idx)
optimal_lambda = optimal_parameters.get('lambda1')
optimal_alpha = optimal_parameters.get('alpha')

# Define asgl class using optimal values
asgl_model = asgl.ASGL(model=model, penalization=penalization, lambda1=optimal_lambda, alpha=optimal_alpha)


MOdel: Adaptive sparse group lasso
Loss function: QRE
    If you are interested in the mean, use MSE, if in the median, use quantile. 
    One big difference is that the mean is more affected by outliers and other extreme data.
The main appeal of quantile regression is that it is more robust than OLS. The downside is that if all assumptions are met, it will be less efficient

This is just a Markdown, now changed